language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

addons:
  apt:
    packages:
      - ca-certificates

php:
  - '5.5'
  - '5.6'
  - '7.0'

before_install:
  - composer self-update

install:
  - composer install

script:
  - composer test
