language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

before_install:
  - composer self-update

install:
  - composer install

before_script:
  - echo "curl.cainfo=$TRAVIS_BUILD_DIR/cacert.pem" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  - vendor/bin/phpunit
