language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

before_install:
  - composer self-update

install:
  - composer install

before_script:
  - if [[ "$TRAVIS_PHP_VERSION" == "7.0" ]]; then wget https://curl.haxx.se/ca/cacert.pem -O /tmp/cacert.pem -np; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "7.0" ]]; then echo 'curl.cainfo=/tmp/cacert.pem' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi

script:
  - vendor/bin/phpunit
